### ISSUE TITLE
file in google drive does not match the code 

### ISSUE THREAD

**Issue by gkyustc** [DirtyHarryLYL/Sandwich#1]
Hi,

Thanks for your impressive work. But I think you uploaded the wrong files in google drive since they do not match the file name and format in the code. 

Regards

**Comment by enlighten0707** [comment]
Hi, what is the specific mismatch/missing?
Currently, we share 4 files, which should be put into a "Data" folder. Is that right?

**Comment by gkyustc** [comment]
Sorry for the late reply. I thought the json file in google drive was the one you used in [this file](https://github.com/DirtyHarryLYL/Sandwich/blob/main/pangea_data/query_collected.ipynb).

**Comment by enlighten0707** [comment]
Now we have uploaded "Label2Node_batch1+2+3.json". Thx :)
